### ISSUE TITLE
Execution Error

### ISSUE THREAD

**Issue by elkyary** [petertodd/replace-by-fee-tools#1]
Hello,
I'm an enginner student, and I'm studying the double spending attack. I have download and build your project replace by fee and your version of bitcoin core but when I execute ./double_spending.py Addr Amount, I receive the error : bitcoin.wallet.CBitcoinadress : Version 111 not a recognized Bitcoin adress.
Can you help me understanding where it come from ?

Thank you

**Comment by elkyary** [comment]
Hello again,
I forgot that I was in testnet, the problem is solved but now I got a error after de 15 seconds sleep when I send the second transaction : bitcoin.rpc.JSONRPCEXCEPTION code -25
Could you help me?

**Comment by petertodd** [comment]
Are you actually running the RBF patch on your local Bitcoin Core node?

Also, once you fix that, mind submitting a patch that checks if you are and errors out if you aren't. :)

**Comment by lclc** [comment]
https://github.com/petertodd/replace-by-fee-tools/blob/a2ece744872c1d66fdfd892b17775f28f86299d3/lib/python-bitcoinlib/bitcoin/rpc.py#L53
https://github.com/bitcoin/bitcoin/blob/master/src/rpcprotocol.h#L53
https://bitcoin.stackexchange.com/questions/tagged/rpc-error-25

Git search / git grep ;)

Seems Bitcoin Core says your transaction is invalid. Probably for the reason Peter Todd just mentioned (not running with RBF patch, so Bitcoin Core drops your attempt to re-spend that output).

**Comment by petertodd** [comment]
@elkyary I assume that fixed your problem? Re-open if not.
